# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'OtherWindow1.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from Seat import Ui_Seat

class Ui_OtherWindow1(object):
    def openseat(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_Seat()
        self.ui.setupUi(self.window)
        self.window.show()
    def setupUi(self, OtherWindow1):
        OtherWindow1.setObjectName("OtherWindow1")
        OtherWindow1.resize(712, 295)
        self.centralwidget = QtWidgets.QWidget(OtherWindow1)
        self.centralwidget.setObjectName("centralwidget")
        self.I9 = QtWidgets.QPushButton(self.centralwidget)
        self.I9.setGeometry(QtCore.QRect(40, 160, 291, 51))
        self.I9.setObjectName("I9")
        self.I9.clicked.connect(self.openseat)

        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(270, 110, 161, 41))
        self.label.setObjectName("label")
        self.I13 = QtWidgets.QPushButton(self.centralwidget)
        self.I13.setGeometry(QtCore.QRect(380, 160, 291, 51))
        self.I13.setObjectName("I13")
        self.I13.clicked.connect(self.openseat)

        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(0, 0, 711, 251))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("Iron man.jpg"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(240, 10, 231, 71))
        self.label_3.setObjectName("label_3")
        self.label_2.raise_()
        self.I9.raise_()
        self.label.raise_()
        self.I13.raise_()
        self.label_3.raise_()
        OtherWindow1.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(OtherWindow1)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 712, 26))
        self.menubar.setObjectName("menubar")
        OtherWindow1.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(OtherWindow1)
        self.statusbar.setObjectName("statusbar")
        OtherWindow1.setStatusBar(self.statusbar)

        self.retranslateUi(OtherWindow1)
        QtCore.QMetaObject.connectSlotsByName(OtherWindow1)

    def retranslateUi(self, OtherWindow1):
        _translate = QtCore.QCoreApplication.translate
        OtherWindow1.setWindowTitle(_translate("OtherWindow1", "MainWindow"))
        self.I9.setText(_translate("OtherWindow1", "9.00"))
        self.label.setText(_translate("OtherWindow1", "<html><head/><body><p align=\"center\"><span style=\" font-size:16pt; color:#fd0000;\">16/12/2020</span></p></body></html>"))
        self.I13.setText(_translate("OtherWindow1", "13.00"))
        self.label_3.setText(_translate("OtherWindow1", "<html><head/><body><p align=\"center\"><span style=\" font-size:28pt; font-weight:600; color:#ff0000;\">Iron man</span></p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    OtherWindow1 = QtWidgets.QMainWindow()
    ui = Ui_OtherWindow1()
    ui.setupUi(OtherWindow1)
    OtherWindow1.show()
    sys.exit(app.exec_())
