# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'OtherWindow3.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from Seat import Ui_Seat

class Ui_OtherWindow3(object):
    def openseat(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_Seat()
        self.ui.setupUi(self.window)
        self.window.show()
    def setupUi(self, OtherWindow3):
        OtherWindow3.setObjectName("OtherWindow3")
        OtherWindow3.resize(712, 294)
        self.centralwidget = QtWidgets.QWidget(OtherWindow3)
        self.centralwidget.setObjectName("centralwidget")

        self.S17 = QtWidgets.QPushButton(self.centralwidget)
        self.S17.setGeometry(QtCore.QRect(40, 170, 291, 51))
        self.S17.setObjectName("S17")
        self.S17.clicked.connect(self.openseat)

        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(320, 120, 71, 20))
        self.label.setObjectName("label")

        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(200, 20, 301, 71))
        self.textBrowser.setObjectName("textBrowser")

        self.S19 = QtWidgets.QPushButton(self.centralwidget)
        self.S19.setGeometry(QtCore.QRect(380, 170, 291, 51))
        self.S19.setObjectName("S19")
        self.S19.clicked.connect(self.openseat)

        OtherWindow3.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(OtherWindow3)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 712, 26))
        self.menubar.setObjectName("menubar")
        OtherWindow3.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(OtherWindow3)
        self.statusbar.setObjectName("statusbar")
        OtherWindow3.setStatusBar(self.statusbar)

        self.retranslateUi(OtherWindow3)
        QtCore.QMetaObject.connectSlotsByName(OtherWindow3)

    def retranslateUi(self, OtherWindow3):
        _translate = QtCore.QCoreApplication.translate
        OtherWindow3.setWindowTitle(_translate("OtherWindow3", "MainWindow"))
        self.S17.setText(_translate("OtherWindow3", "17.30"))
        self.label.setText(_translate("OtherWindow3", "13/12/2020"))
        self.textBrowser.setHtml(_translate("OtherWindow3", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:28pt;\">Soul</span></p></body></html>"))
        self.S19.setText(_translate("OtherWindow3", "19.30"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    OtherWindow3 = QtWidgets.QMainWindow()
    ui = Ui_OtherWindow3()
    ui.setupUi(OtherWindow3)
    OtherWindow3.show()
    sys.exit(app.exec_())
