# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'OtherWindow2.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from Seat import Ui_Seat

class Ui_OtherWindow2(object):
    def openseat(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_Seat()
        self.ui.setupUi(self.window)
        self.window.show()
    def setupUi(self, OtherWindow2):
        OtherWindow2.setObjectName("OtherWindow2")
        OtherWindow2.resize(717, 297)
        self.centralwidget = QtWidgets.QWidget(OtherWindow2)
        self.centralwidget.setObjectName("centralwidget")
        self.K12 = QtWidgets.QPushButton(self.centralwidget)
        self.K12.setGeometry(QtCore.QRect(50, 170, 291, 51))
        self.K12.setObjectName("K12")
        self.K12.clicked.connect(self.openseat)

        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(300, 100, 151, 41))
        self.label.setObjectName("label")
        self.K15 = QtWidgets.QPushButton(self.centralwidget)
        self.K15.setGeometry(QtCore.QRect(390, 170, 291, 51))
        self.K15.setObjectName("K15")
        self.K15.clicked.connect(self.openseat)

        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(180, 10, 411, 61))
        self.label_3.setAcceptDrops(False)
        self.label_3.setAutoFillBackground(False)
        self.label_3.setObjectName("label_3")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(0, 0, 721, 251))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("kimetsu no.jpg"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.label_2.raise_()
        self.K12.raise_()
        self.label.raise_()
        self.K15.raise_()
        self.label_3.raise_()
        OtherWindow2.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(OtherWindow2)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 717, 26))
        self.menubar.setObjectName("menubar")
        OtherWindow2.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(OtherWindow2)
        self.statusbar.setObjectName("statusbar")
        OtherWindow2.setStatusBar(self.statusbar)

        self.retranslateUi(OtherWindow2)
        QtCore.QMetaObject.connectSlotsByName(OtherWindow2)

    def retranslateUi(self, OtherWindow2):
        _translate = QtCore.QCoreApplication.translate
        OtherWindow2.setWindowTitle(_translate("OtherWindow2", "MainWindow"))
        self.K12.setText(_translate("OtherWindow2", "12.00"))
        self.label.setText(_translate("OtherWindow2", "<html><head/><body><p><span style=\" font-size:16pt; color:#55aaff;\">16/12/2020</span></p></body></html>"))
        self.K15.setText(_translate("OtherWindow2", "15.00"))
        self.label_3.setText(_translate("OtherWindow2", "<html><head/><body><p align=\"center\"><span style=\" font-size:28pt; font-weight:600; color:#55aaff;\">Kimetsu no yaiba</span></p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    OtherWindow2 = QtWidgets.QMainWindow()
    ui = Ui_OtherWindow2()
    ui.setupUi(OtherWindow2)
    OtherWindow2.show()
    sys.exit(app.exec_())
