# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'OtherWindow1.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from Seat import Ui_Seat

class Ui_OtherWindow1(object):
    def openseat(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_Seat()
        self.ui.setupUi(self.window)
        self.window.show()
    def setupUi(self, OtherWindow1):
        OtherWindow1.setObjectName("OtherWindow1")
        OtherWindow1.resize(712, 295)
        self.centralwidget = QtWidgets.QWidget(OtherWindow1)
        self.centralwidget.setObjectName("centralwidget")
        self.I9 = QtWidgets.QPushButton(self.centralwidget)
        self.I9.setGeometry(QtCore.QRect(40, 160, 291, 51))
        self.I9.setObjectName("I9")
        self.I9.clicked.connect(self.openseat)

        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(320, 110, 71, 20))
        self.label.setObjectName("label")

        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(200, 10, 301, 71))
        self.textBrowser.setObjectName("textBrowser")

        self.I13 = QtWidgets.QPushButton(self.centralwidget)
        self.I13.setGeometry(QtCore.QRect(380, 160, 291, 51))
        self.I13.setObjectName("I13")
        self.I13.clicked.connect(self.openseat)

        OtherWindow1.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(OtherWindow1)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 712, 26))
        self.menubar.setObjectName("menubar")
        OtherWindow1.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(OtherWindow1)
        self.statusbar.setObjectName("statusbar")
        OtherWindow1.setStatusBar(self.statusbar)

        self.retranslateUi(OtherWindow1)
        QtCore.QMetaObject.connectSlotsByName(OtherWindow1)

    def retranslateUi(self, OtherWindow1):
        _translate = QtCore.QCoreApplication.translate
        OtherWindow1.setWindowTitle(_translate("OtherWindow1", "MainWindow"))
        self.I9.setText(_translate("OtherWindow1", "9.00"))
        self.label.setText(_translate("OtherWindow1", "13/12/2020"))
        self.textBrowser.setHtml(_translate("OtherWindow1", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:28pt;\">Iron man</span></p></body></html>"))
        self.I13.setText(_translate("OtherWindow1", "13.00"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    OtherWindow1 = QtWidgets.QMainWindow()
    ui = Ui_OtherWindow1()
    ui.setupUi(OtherWindow1)
    OtherWindow1.show()
    sys.exit(app.exec_())
