# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'OtherWindow2.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from Seat import Ui_Seat

class Ui_OtherWindow2(object):
    def openseat(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_Seat()
        self.ui.setupUi(self.window)
        self.window.show()
    def setupUi(self, OtherWindow2):
        OtherWindow2.setObjectName("OtherWindow2")
        OtherWindow2.resize(715, 297)
        self.centralwidget = QtWidgets.QWidget(OtherWindow2)
        self.centralwidget.setObjectName("centralwidget")

        self.K12 = QtWidgets.QPushButton(self.centralwidget)
        self.K12.setGeometry(QtCore.QRect(50, 170, 291, 51))
        self.K12.setObjectName("K12")
        self.K12.clicked.connect(self.openseat)

        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(330, 120, 71, 20))
        self.label.setObjectName("label")

        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(160, 20, 401, 71))
        self.textBrowser.setObjectName("textBrowser")

        self.K15 = QtWidgets.QPushButton(self.centralwidget)
        self.K15.setGeometry(QtCore.QRect(390, 170, 291, 51))
        self.K15.setObjectName("K15")
        self.K15.clicked.connect(self.openseat)

        OtherWindow2.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(OtherWindow2)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 715, 26))
        self.menubar.setObjectName("menubar")
        OtherWindow2.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(OtherWindow2)
        self.statusbar.setObjectName("statusbar")
        OtherWindow2.setStatusBar(self.statusbar)

        self.retranslateUi(OtherWindow2)
        QtCore.QMetaObject.connectSlotsByName(OtherWindow2)

    def retranslateUi(self, OtherWindow2):
        _translate = QtCore.QCoreApplication.translate
        OtherWindow2.setWindowTitle(_translate("OtherWindow2", "MainWindow"))
        self.K12.setText(_translate("OtherWindow2", "12.00"))
        self.label.setText(_translate("OtherWindow2", "13/12/2020"))
        self.textBrowser.setHtml(_translate("OtherWindow2", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:28pt;\">Kimetsu no yaiba</span></p></body></html>"))
        self.K15.setText(_translate("OtherWindow2", "15.00"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    OtherWindow2 = QtWidgets.QMainWindow()
    ui = Ui_OtherWindow2()
    ui.setupUi(OtherWindow2)
    OtherWindow2.show()
    sys.exit(app.exec_())
