# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Seat.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Seat(object):
    def buttonClicked1(self):
        self.A1.setEnabled(0)
    def buttonClicked2(self):
        self.A2.setEnabled(0)
    def buttonClicked3(self):
        self.A3.setEnabled(0)
    def buttonClicked4(self):
        self.A4.setEnabled(0)
    def buttonClicked5(self):
        self.A5.setEnabled(0)
    def buttonClicked6(self):
        self.A6.setEnabled(0)
    def buttonClicked7(self):
        self.B1.setEnabled(0)
    def buttonClicked8(self):
        self.B2.setEnabled(0)
    def buttonClicked9(self):
        self.B3.setEnabled(0)
    def buttonClicked10(self):
        self.B4.setEnabled(0)
    def buttonClicked11(self):
        self.B5.setEnabled(0)
    def buttonClicked12(self):
        self.B6.setEnabled(0)
    def buttonClicked13(self):
        self.D1.setEnabled(0)
    def buttonClicked14(self):
        self.D2.setEnabled(0)
    def buttonClicked15(self):
        self.D3.setEnabled(0)
    def buttonClicked16(self):
        self.D4.setEnabled(0)
    def buttonClicked17(self):
        self.D5.setEnabled(0)
    def buttonClicked18(self):
        self.D6.setEnabled(0)
    def buttonClicked19(self):
        self.E1.setEnabled(0)
    def buttonClicked20(self):
        self.E2.setEnabled(0)
    def buttonClicked21(self):
        self.E3.setEnabled(0)
    def buttonClicked22(self):
        self.E4.setEnabled(0)
    def buttonClicked23(self):
        self.E5.setEnabled(0)
    def buttonClicked24(self):
        self.E6.setEnabled(0)
        
    def setupUi(self, Seat):
        Seat.setObjectName("Seat")
        Seat.resize(800, 496)
        self.centralwidget = QtWidgets.QWidget(Seat)
        self.centralwidget.setObjectName("centralwidget")
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(65, 20, 691, 51))
        self.textBrowser.setObjectName("textBrowser")
        self.A1 = QtWidgets.QPushButton(self.centralwidget)
        self.A1.setGeometry(QtCore.QRect(50, 120, 93, 41))
        self.A1.setObjectName("A1")
        self.A1.clicked.connect(self.buttonClicked1)

        self.A2 = QtWidgets.QPushButton(self.centralwidget)
        self.A2.setGeometry(QtCore.QRect(170, 120, 93, 41))
        self.A2.setObjectName("A2")
        self.A2.clicked.connect(self.buttonClicked2)

        self.A3 = QtWidgets.QPushButton(self.centralwidget)
        self.A3.setGeometry(QtCore.QRect(290, 120, 93, 41))
        self.A3.setObjectName("A3")
        self.A3.clicked.connect(self.buttonClicked3)

        self.A4 = QtWidgets.QPushButton(self.centralwidget)
        self.A4.setGeometry(QtCore.QRect(410, 120, 93, 41))
        self.A4.setObjectName("A4")
        self.A4.clicked.connect(self.buttonClicked4)

        self.A5 = QtWidgets.QPushButton(self.centralwidget)
        self.A5.setGeometry(QtCore.QRect(530, 120, 93, 41))
        self.A5.setObjectName("A5")
        self.A5.clicked.connect(self.buttonClicked5)

        self.A6 = QtWidgets.QPushButton(self.centralwidget)
        self.A6.setGeometry(QtCore.QRect(650, 120, 93, 41))
        self.A6.setObjectName("A6")
        self.A6.clicked.connect(self.buttonClicked6)

        self.B6 = QtWidgets.QPushButton(self.centralwidget)
        self.B6.setGeometry(QtCore.QRect(650, 190, 93, 41))
        self.B6.setObjectName("B6")
        self.B6.clicked.connect(self.buttonClicked12)

        self.B5 = QtWidgets.QPushButton(self.centralwidget)
        self.B5.setGeometry(QtCore.QRect(530, 190, 93, 41))
        self.B5.setObjectName("B5")
        self.B5.clicked.connect(self.buttonClicked11)

        self.B2 = QtWidgets.QPushButton(self.centralwidget)
        self.B2.setGeometry(QtCore.QRect(170, 190, 93, 41))
        self.B2.setObjectName("B2")
        self.B2.clicked.connect(self.buttonClicked8)

        self.B3 = QtWidgets.QPushButton(self.centralwidget)
        self.B3.setGeometry(QtCore.QRect(290, 190, 93, 41))
        self.B3.setObjectName("B3")
        self.B3.clicked.connect(self.buttonClicked9)

        self.B4 = QtWidgets.QPushButton(self.centralwidget)
        self.B4.setGeometry(QtCore.QRect(410, 190, 93, 41))
        self.B4.setObjectName("B4")
        self.B4.clicked.connect(self.buttonClicked10)

        self.B1 = QtWidgets.QPushButton(self.centralwidget)
        self.B1.setGeometry(QtCore.QRect(50, 190, 93, 41))
        self.B1.setObjectName("B1")
        self.B1.clicked.connect(self.buttonClicked7)

        self.E1 = QtWidgets.QPushButton(self.centralwidget)
        self.E1.setGeometry(QtCore.QRect(50, 330, 93, 41))
        self.E1.setObjectName("E1")
        self.E1.clicked.connect(self.buttonClicked19)

        self.D5 = QtWidgets.QPushButton(self.centralwidget)
        self.D5.setGeometry(QtCore.QRect(530, 260, 93, 41))
        self.D5.setObjectName("D5")
        self.D5.clicked.connect(self.buttonClicked17)

        self.D2 = QtWidgets.QPushButton(self.centralwidget)
        self.D2.setGeometry(QtCore.QRect(170, 260, 93, 41))
        self.D2.setObjectName("D2")
        self.D2.clicked.connect(self.buttonClicked14)

        self.E2 = QtWidgets.QPushButton(self.centralwidget)
        self.E2.setGeometry(QtCore.QRect(170, 330, 93, 41))
        self.E2.setObjectName("E2")
        self.E2.clicked.connect(self.buttonClicked20)

        self.D3 = QtWidgets.QPushButton(self.centralwidget)
        self.D3.setGeometry(QtCore.QRect(290, 260, 93, 41))
        self.D3.setObjectName("D3")
        self.D3.clicked.connect(self.buttonClicked15)

        self.E3 = QtWidgets.QPushButton(self.centralwidget)
        self.E3.setGeometry(QtCore.QRect(290, 330, 93, 41))
        self.E3.setObjectName("E3")
        self.E3.clicked.connect(self.buttonClicked21)

        self.D4 = QtWidgets.QPushButton(self.centralwidget)
        self.D4.setGeometry(QtCore.QRect(410, 260, 93, 41))
        self.D4.setObjectName("D4")
        self.D4.clicked.connect(self.buttonClicked16)

        self.D1 = QtWidgets.QPushButton(self.centralwidget)
        self.D1.setGeometry(QtCore.QRect(50, 260, 93, 41))
        self.D1.setObjectName("D1")
        self.D1.clicked.connect(self.buttonClicked13)

        self.E6 = QtWidgets.QPushButton(self.centralwidget)
        self.E6.setGeometry(QtCore.QRect(650, 330, 93, 41))
        self.E6.setObjectName("E6")
        self.E6.clicked.connect(self.buttonClicked24)

        self.E4 = QtWidgets.QPushButton(self.centralwidget)
        self.E4.setGeometry(QtCore.QRect(410, 330, 93, 41))
        self.E4.setObjectName("E4")
        self.E4.clicked.connect(self.buttonClicked22)

        self.D6 = QtWidgets.QPushButton(self.centralwidget)
        self.D6.setGeometry(QtCore.QRect(650, 260, 93, 41))
        self.D6.setObjectName("D6")
        self.D6.clicked.connect(self.buttonClicked18)

        self.E5 = QtWidgets.QPushButton(self.centralwidget)
        self.E5.setGeometry(QtCore.QRect(530, 330, 93, 41))
        self.E5.setObjectName("E5")
        self.E5.clicked.connect(self.buttonClicked23)

        self.Next = QtWidgets.QPushButton(self.centralwidget)
        self.Next.setGeometry(QtCore.QRect(350, 400, 101, 31))
        self.Next.setObjectName("Next")

        Seat.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Seat)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        Seat.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Seat)
        self.statusbar.setObjectName("statusbar")
        Seat.setStatusBar(self.statusbar)

        self.retranslateUi(Seat)
        QtCore.QMetaObject.connectSlotsByName(Seat)

    def retranslateUi(self, Seat):
        _translate = QtCore.QCoreApplication.translate
        Seat.setWindowTitle(_translate("Seat", "MainWindow"))
        self.textBrowser.setHtml(_translate("Seat", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:20pt;\">Screen</span></p></body></html>"))
        self.A1.setText(_translate("Seat", "A1"))
        self.A2.setText(_translate("Seat", "A2"))
        self.A3.setText(_translate("Seat", "A3"))
        self.A4.setText(_translate("Seat", "A4"))
        self.A5.setText(_translate("Seat", "A5"))
        self.A6.setText(_translate("Seat", "A6"))
        self.B6.setText(_translate("Seat", "B6"))
        self.B5.setText(_translate("Seat", "B5"))
        self.B2.setText(_translate("Seat", "B2"))
        self.B3.setText(_translate("Seat", "B3"))
        self.B4.setText(_translate("Seat", "B4"))
        self.B1.setText(_translate("Seat", "B1"))
        self.E1.setText(_translate("Seat", "E1"))
        self.D5.setText(_translate("Seat", "D5"))
        self.D2.setText(_translate("Seat", "D2"))
        self.E2.setText(_translate("Seat", "E2"))
        self.D3.setText(_translate("Seat", "D3"))
        self.E3.setText(_translate("Seat", "E3"))
        self.D4.setText(_translate("Seat", "D4"))
        self.D1.setText(_translate("Seat", "D1"))
        self.E6.setText(_translate("Seat", "E6"))
        self.E4.setText(_translate("Seat", "E4"))
        self.D6.setText(_translate("Seat", "D6"))
        self.E5.setText(_translate("Seat", "E5"))
        self.Next.setText(_translate("Seat", "Next"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Seat = QtWidgets.QMainWindow()
    ui = Ui_Seat()
    ui.setupUi(Seat)
    Seat.show()
    sys.exit(app.exec_())
